### ISSUE TITLE
How does the spacing/layout of the content look?

### ISSUE THREAD

**Issue by skimisphat** [skimisphat/split-flap-forma#4]
Hi David,

I built out the content section but I think it might look a little funky in full-screen width vs the width of the mockup images. What tweaking does it need to properly match the vibe of the mockups/what you're going for?

**Comment by djrrb** [comment]
Cool!

You may not have gotten to this yet, but I think he was picturing the opening section occupying the majority of the viewport, so I’d still be curious to see you experiment with that and some kind of scaling that is proportional to the size. (Also it should say Forma DJR Mono, not Forma Mono by DJR)

I think some kind of `max-width` for the content section as a whole could prevent it from getting too wide? Also I believe the headlines are using the black weight (`font-weight: 900`).

**Comment by skimisphat** [comment]
From our chat:
i would say looking at your browser that the font size is maybe bit on the small side, with line height maybe a bit on the tight side?
*in browser
headline looks good
tho maybe there the linespace could get tighter
well maybe not too much because of that big honking wordspace
(in typographic hierarchy theory, margins are bigger than linespaces are bigger than wordspaces are bigger than letterspaces…but in this particular case we may not be able to achieve that)
